development:
  adapter: async
  allowed_request_origins:
    - http://localhost:5173
    - http://127.0.0.1:5173

test:
  adapter: test

production:
  adapter: async
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 1.day
