development:
  adapter: async
  allowed_request_origins:
    - http://localhost:5173
    - http://127.0.0.1:5173

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: rails_chat_api_production
